[package]
name = "si"
version = "0.1.0"
authors = ["SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
colored = "*"
pager = "*"
tempdir = "*"
utf8-chars = "*"

[dev-dependencies]
strip-ansi-escapes = "*"
itertools = "*"
